//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatrizRiesgos.AuthenticatorService1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationContext", Namespace="http://connectivity.service.ews.mincom.com")]
    [System.SerializableAttribute()]
    public partial class OperationContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string applicationClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string districtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool eventDisableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int maxInstancesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string positionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool returnWarningsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MatrizRiesgos.AuthenticatorService1.RunAs runAsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool traceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transactionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string applicationClientId {
            get {
                return this.applicationClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.applicationClientIdField, value) != true)) {
                    this.applicationClientIdField = value;
                    this.RaisePropertyChanged("applicationClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string district {
            get {
                return this.districtField;
            }
            set {
                if ((object.ReferenceEquals(this.districtField, value) != true)) {
                    this.districtField = value;
                    this.RaisePropertyChanged("district");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool eventDisable {
            get {
                return this.eventDisableField;
            }
            set {
                if ((this.eventDisableField.Equals(value) != true)) {
                    this.eventDisableField = value;
                    this.RaisePropertyChanged("eventDisable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int maxInstances {
            get {
                return this.maxInstancesField;
            }
            set {
                if ((this.maxInstancesField.Equals(value) != true)) {
                    this.maxInstancesField = value;
                    this.RaisePropertyChanged("maxInstances");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                if ((object.ReferenceEquals(this.positionField, value) != true)) {
                    this.positionField = value;
                    this.RaisePropertyChanged("position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool returnWarnings {
            get {
                return this.returnWarningsField;
            }
            set {
                if ((this.returnWarningsField.Equals(value) != true)) {
                    this.returnWarningsField = value;
                    this.RaisePropertyChanged("returnWarnings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MatrizRiesgos.AuthenticatorService1.RunAs runAs {
            get {
                return this.runAsField;
            }
            set {
                if ((object.ReferenceEquals(this.runAsField, value) != true)) {
                    this.runAsField = value;
                    this.RaisePropertyChanged("runAs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tenantId {
            get {
                return this.tenantIdField;
            }
            set {
                if ((object.ReferenceEquals(this.tenantIdField, value) != true)) {
                    this.tenantIdField = value;
                    this.RaisePropertyChanged("tenantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool trace {
            get {
                return this.traceField;
            }
            set {
                if ((this.traceField.Equals(value) != true)) {
                    this.traceField = value;
                    this.RaisePropertyChanged("trace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string transaction {
            get {
                return this.transactionField;
            }
            set {
                if ((object.ReferenceEquals(this.transactionField, value) != true)) {
                    this.transactionField = value;
                    this.RaisePropertyChanged("transaction");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RunAs", Namespace="http://connectivity.service.ews.mincom.com")]
    [System.SerializableAttribute()]
    public partial class RunAs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string districtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string positionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string district {
            get {
                return this.districtField;
            }
            set {
                if ((object.ReferenceEquals(this.districtField, value) != true)) {
                    this.districtField = value;
                    this.RaisePropertyChanged("district");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                if ((object.ReferenceEquals(this.positionField, value) != true)) {
                    this.positionField = value;
                    this.RaisePropertyChanged("position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NameValuePair", Namespace="http://connectivity.service.ews.mincom.com")]
    [System.SerializableAttribute()]
    public partial class NameValuePair : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://connectivity.service.ews.mincom.com", ConfigurationName="AuthenticatorService1.Authenticator")]
    public interface Authenticator {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        void authenticate(MatrizRiesgos.AuthenticatorService1.OperationContext context);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task authenticateAsync(MatrizRiesgos.AuthenticatorService1.OperationContext context);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        void flush(MatrizRiesgos.AuthenticatorService1.OperationContext context);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task flushAsync(MatrizRiesgos.AuthenticatorService1.OperationContext context);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="districts")]
        MatrizRiesgos.AuthenticatorService1.NameValuePair[] getDistricts(MatrizRiesgos.AuthenticatorService1.OperationContext context);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="districts")]
        System.Threading.Tasks.Task<MatrizRiesgos.AuthenticatorService1.NameValuePair[]> getDistrictsAsync(MatrizRiesgos.AuthenticatorService1.OperationContext context);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="positions")]
        MatrizRiesgos.AuthenticatorService1.NameValuePair[] getPositions(MatrizRiesgos.AuthenticatorService1.OperationContext context);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="positions")]
        System.Threading.Tasks.Task<MatrizRiesgos.AuthenticatorService1.NameValuePair[]> getPositionsAsync(MatrizRiesgos.AuthenticatorService1.OperationContext context);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthenticatorChannel : MatrizRiesgos.AuthenticatorService1.Authenticator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticatorClient : System.ServiceModel.ClientBase<MatrizRiesgos.AuthenticatorService1.Authenticator>, MatrizRiesgos.AuthenticatorService1.Authenticator {
        
        public AuthenticatorClient() {
        }
        
        public AuthenticatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void authenticate(MatrizRiesgos.AuthenticatorService1.OperationContext context) {
            base.Channel.authenticate(context);
        }
        
        public System.Threading.Tasks.Task authenticateAsync(MatrizRiesgos.AuthenticatorService1.OperationContext context) {
            return base.Channel.authenticateAsync(context);
        }
        
        public void flush(MatrizRiesgos.AuthenticatorService1.OperationContext context) {
            base.Channel.flush(context);
        }
        
        public System.Threading.Tasks.Task flushAsync(MatrizRiesgos.AuthenticatorService1.OperationContext context) {
            return base.Channel.flushAsync(context);
        }
        
        public MatrizRiesgos.AuthenticatorService1.NameValuePair[] getDistricts(MatrizRiesgos.AuthenticatorService1.OperationContext context) {
            return base.Channel.getDistricts(context);
        }
        
        public System.Threading.Tasks.Task<MatrizRiesgos.AuthenticatorService1.NameValuePair[]> getDistrictsAsync(MatrizRiesgos.AuthenticatorService1.OperationContext context) {
            return base.Channel.getDistrictsAsync(context);
        }
        
        public MatrizRiesgos.AuthenticatorService1.NameValuePair[] getPositions(MatrizRiesgos.AuthenticatorService1.OperationContext context) {
            return base.Channel.getPositions(context);
        }
        
        public System.Threading.Tasks.Task<MatrizRiesgos.AuthenticatorService1.NameValuePair[]> getPositionsAsync(MatrizRiesgos.AuthenticatorService1.OperationContext context) {
            return base.Channel.getPositionsAsync(context);
        }
    }
}
