//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatrizRiesgos.GenericScriptService1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", ConfigurationName="GenericScriptService1.GenericScript")]
    public interface GenericScript {
        
        // CODEGEN: El parámetro 'out' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Base))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericScriptDTO[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        MatrizRiesgos.GenericScriptService1.multipleExecuteResponse multipleExecute(MatrizRiesgos.GenericScriptService1.multipleExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.multipleExecuteResponse> multipleExecuteAsync(MatrizRiesgos.GenericScriptService1.multipleExecuteRequest request);
        
        // CODEGEN: El parámetro 'out' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Base))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericScriptDTO[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        MatrizRiesgos.GenericScriptService1.executeForCollectionResponse executeForCollection(MatrizRiesgos.GenericScriptService1.executeForCollectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.executeForCollectionResponse> executeForCollectionAsync(MatrizRiesgos.GenericScriptService1.executeForCollectionRequest request);
        
        // CODEGEN: El parámetro 'out' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Base))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericScriptDTO[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        MatrizRiesgos.GenericScriptService1.multipleUpdateResponse multipleUpdate(MatrizRiesgos.GenericScriptService1.multipleUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.multipleUpdateResponse> multipleUpdateAsync(MatrizRiesgos.GenericScriptService1.multipleUpdateRequest request);
        
        // CODEGEN: El parámetro 'out' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Base))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericScriptDTO[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        MatrizRiesgos.GenericScriptService1.multipleDeleteResponse multipleDelete(MatrizRiesgos.GenericScriptService1.multipleDeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.multipleDeleteResponse> multipleDeleteAsync(MatrizRiesgos.GenericScriptService1.multipleDeleteRequest request);
        
        // CODEGEN: El parámetro 'out' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Base))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericScriptDTO[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        MatrizRiesgos.GenericScriptService1.createResponse create(MatrizRiesgos.GenericScriptService1.createRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.createResponse> createAsync(MatrizRiesgos.GenericScriptService1.createRequest request);
        
        // CODEGEN: El parámetro 'out' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Base))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericScriptDTO[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        MatrizRiesgos.GenericScriptService1.updateResponse update(MatrizRiesgos.GenericScriptService1.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.updateResponse> updateAsync(MatrizRiesgos.GenericScriptService1.updateRequest request);
        
        // CODEGEN: El parámetro 'out' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Base))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericScriptDTO[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        MatrizRiesgos.GenericScriptService1.getTypesResponse getTypes(MatrizRiesgos.GenericScriptService1.getTypesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.getTypesResponse> getTypesAsync(MatrizRiesgos.GenericScriptService1.getTypesRequest request);
        
        // CODEGEN: El parámetro 'out' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Base))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericScriptDTO[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        MatrizRiesgos.GenericScriptService1.deleteResponse delete(MatrizRiesgos.GenericScriptService1.deleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.deleteResponse> deleteAsync(MatrizRiesgos.GenericScriptService1.deleteRequest request);
        
        // CODEGEN: El parámetro 'out' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Base))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericScriptDTO[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        MatrizRiesgos.GenericScriptService1.executeResponse execute(MatrizRiesgos.GenericScriptService1.executeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.executeResponse> executeAsync(MatrizRiesgos.GenericScriptService1.executeRequest request);
        
        // CODEGEN: El parámetro 'out' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Base))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericScriptDTO[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        MatrizRiesgos.GenericScriptService1.multipleCreateResponse multipleCreate(MatrizRiesgos.GenericScriptService1.multipleCreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.multipleCreateResponse> multipleCreateAsync(MatrizRiesgos.GenericScriptService1.multipleCreateRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connectivity.service.ews.mincom.com")]
    public partial class OperationContext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string applicationClientIdField;
        
        private string districtField;
        
        private bool eventDisableField;
        
        private bool eventDisableFieldSpecified;
        
        private int maxInstancesField;
        
        private bool maxInstancesFieldSpecified;
        
        private string positionField;
        
        private bool returnWarningsField;
        
        private bool returnWarningsFieldSpecified;
        
        private RunAs runAsField;
        
        private string tenantIdField;
        
        private bool traceField;
        
        private bool traceFieldSpecified;
        
        private string transactionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string applicationClientId {
            get {
                return this.applicationClientIdField;
            }
            set {
                this.applicationClientIdField = value;
                this.RaisePropertyChanged("applicationClientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string district {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
                this.RaisePropertyChanged("district");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool eventDisable {
            get {
                return this.eventDisableField;
            }
            set {
                this.eventDisableField = value;
                this.RaisePropertyChanged("eventDisable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventDisableSpecified {
            get {
                return this.eventDisableFieldSpecified;
            }
            set {
                this.eventDisableFieldSpecified = value;
                this.RaisePropertyChanged("eventDisableSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int maxInstances {
            get {
                return this.maxInstancesField;
            }
            set {
                this.maxInstancesField = value;
                this.RaisePropertyChanged("maxInstances");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxInstancesSpecified {
            get {
                return this.maxInstancesFieldSpecified;
            }
            set {
                this.maxInstancesFieldSpecified = value;
                this.RaisePropertyChanged("maxInstancesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool returnWarnings {
            get {
                return this.returnWarningsField;
            }
            set {
                this.returnWarningsField = value;
                this.RaisePropertyChanged("returnWarnings");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnWarningsSpecified {
            get {
                return this.returnWarningsFieldSpecified;
            }
            set {
                this.returnWarningsFieldSpecified = value;
                this.RaisePropertyChanged("returnWarningsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public RunAs runAs {
            get {
                return this.runAsField;
            }
            set {
                this.runAsField = value;
                this.RaisePropertyChanged("runAs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string tenantId {
            get {
                return this.tenantIdField;
            }
            set {
                this.tenantIdField = value;
                this.RaisePropertyChanged("tenantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool trace {
            get {
                return this.traceField;
            }
            set {
                this.traceField = value;
                this.RaisePropertyChanged("trace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool traceSpecified {
            get {
                return this.traceFieldSpecified;
            }
            set {
                this.traceFieldSpecified = value;
                this.RaisePropertyChanged("traceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string transaction {
            get {
                return this.transactionField;
            }
            set {
                this.transactionField = value;
                this.RaisePropertyChanged("transaction");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connectivity.service.ews.mincom.com")]
    public partial class RunAs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string districtField;
        
        private string positionField;
        
        private string userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string district {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
                this.RaisePropertyChanged("district");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ellipse.mincom.com")]
    public partial class ServiceRequiredAttributes : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericScriptServiceResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ellipse.mincom.com")]
    public abstract partial class BaseServiceResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error[] errorsField;
        
        private Message[] informationalMessagesField;
        
        private Warning[] warningsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://errors.ellipse.mincom.com")]
        public Error[] errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://errors.ellipse.mincom.com")]
        public Message[] informationalMessages {
            get {
                return this.informationalMessagesField;
            }
            set {
                this.informationalMessagesField = value;
                this.RaisePropertyChanged("informationalMessages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://errors.ellipse.mincom.com")]
        public Warning[] warnings {
            get {
                return this.warningsField;
            }
            set {
                this.warningsField = value;
                this.RaisePropertyChanged("warnings");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://errors.ellipse.mincom.com")]
    public partial class Error : Message {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Error))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Warning))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://errors.ellipse.mincom.com")]
    public partial class Message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldIdField;
        
        private int fieldIndexField;
        
        private bool fieldIndexFieldSpecified;
        
        private bool localisableField;
        
        private bool localisableFieldSpecified;
        
        private string messageIdField;
        
        private string messageInstanceField;
        
        private string messageTextField;
        
        private string parentInstanceField;
        
        private string userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fieldId {
            get {
                return this.fieldIdField;
            }
            set {
                this.fieldIdField = value;
                this.RaisePropertyChanged("fieldId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int fieldIndex {
            get {
                return this.fieldIndexField;
            }
            set {
                this.fieldIndexField = value;
                this.RaisePropertyChanged("fieldIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fieldIndexSpecified {
            get {
                return this.fieldIndexFieldSpecified;
            }
            set {
                this.fieldIndexFieldSpecified = value;
                this.RaisePropertyChanged("fieldIndexSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool localisable {
            get {
                return this.localisableField;
            }
            set {
                this.localisableField = value;
                this.RaisePropertyChanged("localisable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool localisableSpecified {
            get {
                return this.localisableFieldSpecified;
            }
            set {
                this.localisableFieldSpecified = value;
                this.RaisePropertyChanged("localisableSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("messageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string messageInstance {
            get {
                return this.messageInstanceField;
            }
            set {
                this.messageInstanceField = value;
                this.RaisePropertyChanged("messageInstance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string messageText {
            get {
                return this.messageTextField;
            }
            set {
                this.messageTextField = value;
                this.RaisePropertyChanged("messageText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string parentInstance {
            get {
                return this.parentInstanceField;
            }
            set {
                this.parentInstanceField = value;
                this.RaisePropertyChanged("parentInstance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://errors.ellipse.mincom.com")]
    public partial class Warning : Message {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericScriptServiceResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ellipse.mincom.com")]
    public partial class ServiceResult : BaseServiceResult {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://instances.m1000.types.ellipse.mincom.com")]
    public partial class GenericScriptServiceResult : ServiceResult {
        
        private GenericScriptDTO genericScriptDTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public GenericScriptDTO genericScriptDTO {
            get {
                return this.genericScriptDTOField;
            }
            set {
                this.genericScriptDTOField = value;
                this.RaisePropertyChanged("genericScriptDTO");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://instances.m1000.types.ellipse.mincom.com")]
    public partial class GenericScriptDTO : ServiceDTO {
        
        private string scriptNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string scriptName {
            get {
                return this.scriptNameField;
            }
            set {
                this.scriptNameField = value;
                this.RaisePropertyChanged("scriptName");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractSearchParam))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericScriptSearchParam))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericScriptDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ellipse.mincom.com")]
    public abstract partial class ServiceDTO : Base {
        
        private Attribute[] customAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://attribute.ellipse.mincom.com")]
        public Attribute[] customAttributes {
            get {
                return this.customAttributesField;
            }
            set {
                this.customAttributesField = value;
                this.RaisePropertyChanged("customAttributes");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://attribute.ellipse.mincom.com")]
    public partial class Attribute : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dataTypeField;
        
        private string nameField;
        
        private string namespaceField;
        
        private anyType2anyTypeMapEntry[] propertiesField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
                this.RaisePropertyChanged("dataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string @namespace {
            get {
                return this.namespaceField;
            }
            set {
                this.namespaceField = value;
                this.RaisePropertyChanged("namespace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Namespace="http://genericscript.m1000.service.ellipse.mincom.com", IsNullable=false)]
        public anyType2anyTypeMapEntry[] properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
                this.RaisePropertyChanged("properties");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://genericscript.m1000.service.ellipse.mincom.com")]
    public partial class anyType2anyTypeMapEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public object key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractSearchParam))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericScriptSearchParam))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericScriptDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://instances.base.types.ellipse.mincom.com")]
    public abstract partial class Base : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericScriptSearchParam))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ellipse.mincom.com")]
    public abstract partial class AbstractSearchParam : ServiceDTO {
        
        private ServiceRequiredAttributes serviceRequiredAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ServiceRequiredAttributes serviceRequiredAttributes {
            get {
                return this.serviceRequiredAttributesField;
            }
            set {
                this.serviceRequiredAttributesField = value;
                this.RaisePropertyChanged("serviceRequiredAttributes");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://instances.m1000.types.ellipse.mincom.com")]
    public partial class GenericScriptSearchParam : AbstractSearchParam {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multipleExecute", WrapperNamespace="http://genericscript.m1000.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class multipleExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://instances.m1000.types.ellipse.mincom.com")]
        public MatrizRiesgos.GenericScriptService1.GenericScriptDTO[] inputDtos;
        
        public multipleExecuteRequest() {
        }
        
        public multipleExecuteRequest(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO[] inputDtos) {
            this.context = context;
            this.inputDtos = inputDtos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multipleExecuteResponse", WrapperNamespace="http://genericscript.m1000.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class multipleExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://instances.m1000.types.ellipse.mincom.com")]
        public MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult[] @out;
        
        public multipleExecuteResponse() {
        }
        
        public multipleExecuteResponse(MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult[] @out) {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="executeForCollection", WrapperNamespace="http://genericscript.m1000.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class executeForCollectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.GenericScriptSearchParam searchParams;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.GenericScriptDTO restart;
        
        public executeForCollectionRequest() {
        }
        
        public executeForCollectionRequest(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptSearchParam searchParams, MatrizRiesgos.GenericScriptService1.GenericScriptDTO restart) {
            this.context = context;
            this.searchParams = searchParams;
            this.restart = restart;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="executeForCollectionResponse", WrapperNamespace="http://genericscript.m1000.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class executeForCollectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://instances.m1000.types.ellipse.mincom.com")]
        public MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult[] @out;
        
        public executeForCollectionResponse() {
        }
        
        public executeForCollectionResponse(MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult[] @out) {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multipleUpdate", WrapperNamespace="http://genericscript.m1000.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class multipleUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://instances.m1000.types.ellipse.mincom.com")]
        public MatrizRiesgos.GenericScriptService1.GenericScriptDTO[] inputDtos;
        
        public multipleUpdateRequest() {
        }
        
        public multipleUpdateRequest(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO[] inputDtos) {
            this.context = context;
            this.inputDtos = inputDtos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multipleUpdateResponse", WrapperNamespace="http://genericscript.m1000.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class multipleUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://instances.m1000.types.ellipse.mincom.com")]
        public MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult[] @out;
        
        public multipleUpdateResponse() {
        }
        
        public multipleUpdateResponse(MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult[] @out) {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multipleDelete", WrapperNamespace="http://genericscript.m1000.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class multipleDeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://instances.m1000.types.ellipse.mincom.com")]
        public MatrizRiesgos.GenericScriptService1.GenericScriptDTO[] inputDtos;
        
        public multipleDeleteRequest() {
        }
        
        public multipleDeleteRequest(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO[] inputDtos) {
            this.context = context;
            this.inputDtos = inputDtos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multipleDeleteResponse", WrapperNamespace="http://genericscript.m1000.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class multipleDeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://instances.m1000.types.ellipse.mincom.com")]
        public MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult[] @out;
        
        public multipleDeleteResponse() {
        }
        
        public multipleDeleteResponse(MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult[] @out) {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="create", WrapperNamespace="http://genericscript.m1000.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class createRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.GenericScriptDTO serviceDTO;
        
        public createRequest() {
        }
        
        public createRequest(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO serviceDTO) {
            this.context = context;
            this.serviceDTO = serviceDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createResponse", WrapperNamespace="http://genericscript.m1000.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class createResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult @out;
        
        public createResponse() {
        }
        
        public createResponse(MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult @out) {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="update", WrapperNamespace="http://genericscript.m1000.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.GenericScriptDTO serviceDTO;
        
        public updateRequest() {
        }
        
        public updateRequest(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO serviceDTO) {
            this.context = context;
            this.serviceDTO = serviceDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateResponse", WrapperNamespace="http://genericscript.m1000.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult @out;
        
        public updateResponse() {
        }
        
        public updateResponse(MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult @out) {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTypes", WrapperNamespace="http://genericscript.m1000.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class getTypesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.GenericScriptSearchParam searchParams;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.GenericScriptDTO restart;
        
        public getTypesRequest() {
        }
        
        public getTypesRequest(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptSearchParam searchParams, MatrizRiesgos.GenericScriptService1.GenericScriptDTO restart) {
            this.context = context;
            this.searchParams = searchParams;
            this.restart = restart;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTypesResponse", WrapperNamespace="http://genericscript.m1000.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class getTypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://instances.m1000.types.ellipse.mincom.com")]
        public MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult[] @out;
        
        public getTypesResponse() {
        }
        
        public getTypesResponse(MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult[] @out) {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://genericscript.m1000.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class deleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.GenericScriptDTO serviceDTO;
        
        public deleteRequest() {
        }
        
        public deleteRequest(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO serviceDTO) {
            this.context = context;
            this.serviceDTO = serviceDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://genericscript.m1000.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class deleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult @out;
        
        public deleteResponse() {
        }
        
        public deleteResponse(MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult @out) {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="execute", WrapperNamespace="http://genericscript.m1000.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class executeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.GenericScriptDTO serviceDTO;
        
        public executeRequest() {
        }
        
        public executeRequest(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO serviceDTO) {
            this.context = context;
            this.serviceDTO = serviceDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="executeResponse", WrapperNamespace="http://genericscript.m1000.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class executeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult @out;
        
        public executeResponse() {
        }
        
        public executeResponse(MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult @out) {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multipleCreate", WrapperNamespace="http://genericscript.m1000.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class multipleCreateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrizRiesgos.GenericScriptService1.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://instances.m1000.types.ellipse.mincom.com")]
        public MatrizRiesgos.GenericScriptService1.GenericScriptDTO[] inputDtos;
        
        public multipleCreateRequest() {
        }
        
        public multipleCreateRequest(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO[] inputDtos) {
            this.context = context;
            this.inputDtos = inputDtos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multipleCreateResponse", WrapperNamespace="http://genericscript.m1000.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class multipleCreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://genericscript.m1000.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://instances.m1000.types.ellipse.mincom.com")]
        public MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult[] @out;
        
        public multipleCreateResponse() {
        }
        
        public multipleCreateResponse(MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult[] @out) {
            this.@out = @out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GenericScriptChannel : MatrizRiesgos.GenericScriptService1.GenericScript, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenericScriptClient : System.ServiceModel.ClientBase<MatrizRiesgos.GenericScriptService1.GenericScript>, MatrizRiesgos.GenericScriptService1.GenericScript {
        
        public GenericScriptClient() {
        }
        
        public GenericScriptClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GenericScriptClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenericScriptClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenericScriptClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MatrizRiesgos.GenericScriptService1.multipleExecuteResponse MatrizRiesgos.GenericScriptService1.GenericScript.multipleExecute(MatrizRiesgos.GenericScriptService1.multipleExecuteRequest request) {
            return base.Channel.multipleExecute(request);
        }
        
        public MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult[] multipleExecute(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO[] inputDtos) {
            MatrizRiesgos.GenericScriptService1.multipleExecuteRequest inValue = new MatrizRiesgos.GenericScriptService1.multipleExecuteRequest();
            inValue.context = context;
            inValue.inputDtos = inputDtos;
            MatrizRiesgos.GenericScriptService1.multipleExecuteResponse retVal = ((MatrizRiesgos.GenericScriptService1.GenericScript)(this)).multipleExecute(inValue);
            return retVal.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.multipleExecuteResponse> MatrizRiesgos.GenericScriptService1.GenericScript.multipleExecuteAsync(MatrizRiesgos.GenericScriptService1.multipleExecuteRequest request) {
            return base.Channel.multipleExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.multipleExecuteResponse> multipleExecuteAsync(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO[] inputDtos) {
            MatrizRiesgos.GenericScriptService1.multipleExecuteRequest inValue = new MatrizRiesgos.GenericScriptService1.multipleExecuteRequest();
            inValue.context = context;
            inValue.inputDtos = inputDtos;
            return ((MatrizRiesgos.GenericScriptService1.GenericScript)(this)).multipleExecuteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MatrizRiesgos.GenericScriptService1.executeForCollectionResponse MatrizRiesgos.GenericScriptService1.GenericScript.executeForCollection(MatrizRiesgos.GenericScriptService1.executeForCollectionRequest request) {
            return base.Channel.executeForCollection(request);
        }
        
        public MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult[] executeForCollection(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptSearchParam searchParams, MatrizRiesgos.GenericScriptService1.GenericScriptDTO restart) {
            MatrizRiesgos.GenericScriptService1.executeForCollectionRequest inValue = new MatrizRiesgos.GenericScriptService1.executeForCollectionRequest();
            inValue.context = context;
            inValue.searchParams = searchParams;
            inValue.restart = restart;
            MatrizRiesgos.GenericScriptService1.executeForCollectionResponse retVal = ((MatrizRiesgos.GenericScriptService1.GenericScript)(this)).executeForCollection(inValue);
            return retVal.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.executeForCollectionResponse> MatrizRiesgos.GenericScriptService1.GenericScript.executeForCollectionAsync(MatrizRiesgos.GenericScriptService1.executeForCollectionRequest request) {
            return base.Channel.executeForCollectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.executeForCollectionResponse> executeForCollectionAsync(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptSearchParam searchParams, MatrizRiesgos.GenericScriptService1.GenericScriptDTO restart) {
            MatrizRiesgos.GenericScriptService1.executeForCollectionRequest inValue = new MatrizRiesgos.GenericScriptService1.executeForCollectionRequest();
            inValue.context = context;
            inValue.searchParams = searchParams;
            inValue.restart = restart;
            return ((MatrizRiesgos.GenericScriptService1.GenericScript)(this)).executeForCollectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MatrizRiesgos.GenericScriptService1.multipleUpdateResponse MatrizRiesgos.GenericScriptService1.GenericScript.multipleUpdate(MatrizRiesgos.GenericScriptService1.multipleUpdateRequest request) {
            return base.Channel.multipleUpdate(request);
        }
        
        public MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult[] multipleUpdate(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO[] inputDtos) {
            MatrizRiesgos.GenericScriptService1.multipleUpdateRequest inValue = new MatrizRiesgos.GenericScriptService1.multipleUpdateRequest();
            inValue.context = context;
            inValue.inputDtos = inputDtos;
            MatrizRiesgos.GenericScriptService1.multipleUpdateResponse retVal = ((MatrizRiesgos.GenericScriptService1.GenericScript)(this)).multipleUpdate(inValue);
            return retVal.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.multipleUpdateResponse> MatrizRiesgos.GenericScriptService1.GenericScript.multipleUpdateAsync(MatrizRiesgos.GenericScriptService1.multipleUpdateRequest request) {
            return base.Channel.multipleUpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.multipleUpdateResponse> multipleUpdateAsync(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO[] inputDtos) {
            MatrizRiesgos.GenericScriptService1.multipleUpdateRequest inValue = new MatrizRiesgos.GenericScriptService1.multipleUpdateRequest();
            inValue.context = context;
            inValue.inputDtos = inputDtos;
            return ((MatrizRiesgos.GenericScriptService1.GenericScript)(this)).multipleUpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MatrizRiesgos.GenericScriptService1.multipleDeleteResponse MatrizRiesgos.GenericScriptService1.GenericScript.multipleDelete(MatrizRiesgos.GenericScriptService1.multipleDeleteRequest request) {
            return base.Channel.multipleDelete(request);
        }
        
        public MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult[] multipleDelete(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO[] inputDtos) {
            MatrizRiesgos.GenericScriptService1.multipleDeleteRequest inValue = new MatrizRiesgos.GenericScriptService1.multipleDeleteRequest();
            inValue.context = context;
            inValue.inputDtos = inputDtos;
            MatrizRiesgos.GenericScriptService1.multipleDeleteResponse retVal = ((MatrizRiesgos.GenericScriptService1.GenericScript)(this)).multipleDelete(inValue);
            return retVal.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.multipleDeleteResponse> MatrizRiesgos.GenericScriptService1.GenericScript.multipleDeleteAsync(MatrizRiesgos.GenericScriptService1.multipleDeleteRequest request) {
            return base.Channel.multipleDeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.multipleDeleteResponse> multipleDeleteAsync(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO[] inputDtos) {
            MatrizRiesgos.GenericScriptService1.multipleDeleteRequest inValue = new MatrizRiesgos.GenericScriptService1.multipleDeleteRequest();
            inValue.context = context;
            inValue.inputDtos = inputDtos;
            return ((MatrizRiesgos.GenericScriptService1.GenericScript)(this)).multipleDeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MatrizRiesgos.GenericScriptService1.createResponse MatrizRiesgos.GenericScriptService1.GenericScript.create(MatrizRiesgos.GenericScriptService1.createRequest request) {
            return base.Channel.create(request);
        }
        
        public MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult create(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO serviceDTO) {
            MatrizRiesgos.GenericScriptService1.createRequest inValue = new MatrizRiesgos.GenericScriptService1.createRequest();
            inValue.context = context;
            inValue.serviceDTO = serviceDTO;
            MatrizRiesgos.GenericScriptService1.createResponse retVal = ((MatrizRiesgos.GenericScriptService1.GenericScript)(this)).create(inValue);
            return retVal.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.createResponse> MatrizRiesgos.GenericScriptService1.GenericScript.createAsync(MatrizRiesgos.GenericScriptService1.createRequest request) {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.createResponse> createAsync(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO serviceDTO) {
            MatrizRiesgos.GenericScriptService1.createRequest inValue = new MatrizRiesgos.GenericScriptService1.createRequest();
            inValue.context = context;
            inValue.serviceDTO = serviceDTO;
            return ((MatrizRiesgos.GenericScriptService1.GenericScript)(this)).createAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MatrizRiesgos.GenericScriptService1.updateResponse MatrizRiesgos.GenericScriptService1.GenericScript.update(MatrizRiesgos.GenericScriptService1.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult update(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO serviceDTO) {
            MatrizRiesgos.GenericScriptService1.updateRequest inValue = new MatrizRiesgos.GenericScriptService1.updateRequest();
            inValue.context = context;
            inValue.serviceDTO = serviceDTO;
            MatrizRiesgos.GenericScriptService1.updateResponse retVal = ((MatrizRiesgos.GenericScriptService1.GenericScript)(this)).update(inValue);
            return retVal.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.updateResponse> MatrizRiesgos.GenericScriptService1.GenericScript.updateAsync(MatrizRiesgos.GenericScriptService1.updateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.updateResponse> updateAsync(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO serviceDTO) {
            MatrizRiesgos.GenericScriptService1.updateRequest inValue = new MatrizRiesgos.GenericScriptService1.updateRequest();
            inValue.context = context;
            inValue.serviceDTO = serviceDTO;
            return ((MatrizRiesgos.GenericScriptService1.GenericScript)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MatrizRiesgos.GenericScriptService1.getTypesResponse MatrizRiesgos.GenericScriptService1.GenericScript.getTypes(MatrizRiesgos.GenericScriptService1.getTypesRequest request) {
            return base.Channel.getTypes(request);
        }
        
        public MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult[] getTypes(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptSearchParam searchParams, MatrizRiesgos.GenericScriptService1.GenericScriptDTO restart) {
            MatrizRiesgos.GenericScriptService1.getTypesRequest inValue = new MatrizRiesgos.GenericScriptService1.getTypesRequest();
            inValue.context = context;
            inValue.searchParams = searchParams;
            inValue.restart = restart;
            MatrizRiesgos.GenericScriptService1.getTypesResponse retVal = ((MatrizRiesgos.GenericScriptService1.GenericScript)(this)).getTypes(inValue);
            return retVal.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.getTypesResponse> MatrizRiesgos.GenericScriptService1.GenericScript.getTypesAsync(MatrizRiesgos.GenericScriptService1.getTypesRequest request) {
            return base.Channel.getTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.getTypesResponse> getTypesAsync(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptSearchParam searchParams, MatrizRiesgos.GenericScriptService1.GenericScriptDTO restart) {
            MatrizRiesgos.GenericScriptService1.getTypesRequest inValue = new MatrizRiesgos.GenericScriptService1.getTypesRequest();
            inValue.context = context;
            inValue.searchParams = searchParams;
            inValue.restart = restart;
            return ((MatrizRiesgos.GenericScriptService1.GenericScript)(this)).getTypesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MatrizRiesgos.GenericScriptService1.deleteResponse MatrizRiesgos.GenericScriptService1.GenericScript.delete(MatrizRiesgos.GenericScriptService1.deleteRequest request) {
            return base.Channel.delete(request);
        }
        
        public MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult delete(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO serviceDTO) {
            MatrizRiesgos.GenericScriptService1.deleteRequest inValue = new MatrizRiesgos.GenericScriptService1.deleteRequest();
            inValue.context = context;
            inValue.serviceDTO = serviceDTO;
            MatrizRiesgos.GenericScriptService1.deleteResponse retVal = ((MatrizRiesgos.GenericScriptService1.GenericScript)(this)).delete(inValue);
            return retVal.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.deleteResponse> MatrizRiesgos.GenericScriptService1.GenericScript.deleteAsync(MatrizRiesgos.GenericScriptService1.deleteRequest request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.deleteResponse> deleteAsync(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO serviceDTO) {
            MatrizRiesgos.GenericScriptService1.deleteRequest inValue = new MatrizRiesgos.GenericScriptService1.deleteRequest();
            inValue.context = context;
            inValue.serviceDTO = serviceDTO;
            return ((MatrizRiesgos.GenericScriptService1.GenericScript)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MatrizRiesgos.GenericScriptService1.executeResponse MatrizRiesgos.GenericScriptService1.GenericScript.execute(MatrizRiesgos.GenericScriptService1.executeRequest request) {
            return base.Channel.execute(request);
        }
        
        public MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult execute(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO serviceDTO) {
            MatrizRiesgos.GenericScriptService1.executeRequest inValue = new MatrizRiesgos.GenericScriptService1.executeRequest();
            inValue.context = context;
            inValue.serviceDTO = serviceDTO;
            MatrizRiesgos.GenericScriptService1.executeResponse retVal = ((MatrizRiesgos.GenericScriptService1.GenericScript)(this)).execute(inValue);
            return retVal.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.executeResponse> MatrizRiesgos.GenericScriptService1.GenericScript.executeAsync(MatrizRiesgos.GenericScriptService1.executeRequest request) {
            return base.Channel.executeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.executeResponse> executeAsync(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO serviceDTO) {
            MatrizRiesgos.GenericScriptService1.executeRequest inValue = new MatrizRiesgos.GenericScriptService1.executeRequest();
            inValue.context = context;
            inValue.serviceDTO = serviceDTO;
            return ((MatrizRiesgos.GenericScriptService1.GenericScript)(this)).executeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MatrizRiesgos.GenericScriptService1.multipleCreateResponse MatrizRiesgos.GenericScriptService1.GenericScript.multipleCreate(MatrizRiesgos.GenericScriptService1.multipleCreateRequest request) {
            return base.Channel.multipleCreate(request);
        }
        
        public MatrizRiesgos.GenericScriptService1.GenericScriptServiceResult[] multipleCreate(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO[] inputDtos) {
            MatrizRiesgos.GenericScriptService1.multipleCreateRequest inValue = new MatrizRiesgos.GenericScriptService1.multipleCreateRequest();
            inValue.context = context;
            inValue.inputDtos = inputDtos;
            MatrizRiesgos.GenericScriptService1.multipleCreateResponse retVal = ((MatrizRiesgos.GenericScriptService1.GenericScript)(this)).multipleCreate(inValue);
            return retVal.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.multipleCreateResponse> MatrizRiesgos.GenericScriptService1.GenericScript.multipleCreateAsync(MatrizRiesgos.GenericScriptService1.multipleCreateRequest request) {
            return base.Channel.multipleCreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<MatrizRiesgos.GenericScriptService1.multipleCreateResponse> multipleCreateAsync(MatrizRiesgos.GenericScriptService1.OperationContext context, MatrizRiesgos.GenericScriptService1.GenericScriptDTO[] inputDtos) {
            MatrizRiesgos.GenericScriptService1.multipleCreateRequest inValue = new MatrizRiesgos.GenericScriptService1.multipleCreateRequest();
            inValue.context = context;
            inValue.inputDtos = inputDtos;
            return ((MatrizRiesgos.GenericScriptService1.GenericScript)(this)).multipleCreateAsync(inValue);
        }
    }
}
